// -------- Markdown Report Formatter --------
import { formatHeader } from './helpers/format-header.js';
import { formatSummary } from './helpers/format-summary.js';
import { formatKeyConflicts } from './helpers/format-key-conflicts.js';
import { formatNewCodePeriodWarnings } from './helpers/format-ncp-warnings.js';
import { formatServerSteps } from './helpers/format-server-steps.js';
import { formatOrgResults } from './helpers/format-org-results.js';
import { formatProblemProjects } from './helpers/format-problem-projects.js';
import { formatAllProjects } from './helpers/format-all-projects.js';
import { formatFailedAssignments } from './helpers/format-failed-assignments.js';
import { formatEnvironment } from './helpers/format-environment.js';
import { formatConfiguration } from './helpers/format-configuration.js';

export function formatMarkdownReport(results) {
  const sections = [
    formatHeader(results), formatSummary(results),
    formatKeyConflicts(results), formatNewCodePeriodWarnings(results),
    formatServerSteps(results), formatOrgResults(results),
    formatProblemProjects(results), formatAllProjects(results),
    formatFailedAssignments(results), formatEnvironment(results),
    formatConfiguration(results), '---\n*Generated by CloudVoyager*\n',
  ];
  return sections.filter(Boolean).join('\n');
}
