# -------- Project Identification --------
sonar.projectKey=sonar-solutions_cloudvoyager
sonar.organization=sonar-solutions
sonar.projectName=CloudVoyager

# -------- Source Configuration --------
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js

# -------- Coverage Reporting --------
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=test/**/*,scripts/**/*,desktop/**/*,compliance/**/*

# -------- Analysis Exclusions --------
sonar.exclusions=desktop/**/*,dist/**/*,node_modules/**/*,coverage/**/*,.github/**/*
