# -------- Project Identification --------
sonar.projectKey=sonar-solutions_cloudvoyager
sonar.organization=sonar-solutions
sonar.projectName=CloudVoyager

# -------- Source Configuration --------
sonar.sources=src

# -------- Analysis Exclusions --------
sonar.exclusions=desktop/**/*,dist/**/*,node_modules/**/*,coverage/**/*,.github/**/*
