import { formatProjectSection } from './helpers/format-project-section.js';

// -------- Format Issues Delta Report --------

/** Format the per-project issues delta data as a markdown string. */
export function formatIssuesDeltaReport(results) {
  if (!results.issuesDeltaData) return null;
  const { generatedAt, summary, projects } = results.issuesDeltaData;

  const lines = [
    '# Project Issues Delta Report\n',
    `Generated: ${generatedAt}\n`,
    '## Summary\n',
    '| Metric | Count |',
    '|--------|-------|',
    `| Projects Compared | ${summary.projectsCompared} |`,
    `| Issues disappeared (in SQ, not in SC) | ${summary.totalDisappeared} |`,
    `| Issues appeared (in SC, not in SQ) | ${summary.totalAppeared} |`,
    '',
    '> Differences are caused by rule changes between SonarQube and SonarCloud quality profiles.\n',
    '## Per-Project Breakdown\n',
    ...projects.map(formatProjectSection),
    '---\n*Generated by CloudVoyager*\n',
  ];

  return lines.join('\n');
}
