// -------- Build Footer --------

export function buildFooter() {
  return [
    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: '#cccccc' }], margin: [0, 20, 0, 5] },
    { text: 'Generated by CloudVoyager', style: 'small', alignment: 'center' },
  ];
}
