// -------- Executive Summary Markdown Formatter --------
import { computeProjectStats, computeOverallStatus, computeTotalDurationMs } from '../shared.js';
import { formatHeader } from './helpers/format-header.js';
import { formatOverallStatus } from './helpers/format-overall-status.js';
import { formatKeyMetrics } from './helpers/format-key-metrics.js';
import { formatWarningsAndRisks } from './helpers/format-warnings.js';
import { formatActionItems } from './helpers/format-action-items.js';
import { formatFailedProjects } from './helpers/format-failed-projects.js';

export function formatExecutiveSummaryMarkdown(results) {
  const stats = computeProjectStats(results);
  const overallStatus = computeOverallStatus(stats);
  const durationMs = computeTotalDurationMs(results);
  const sections = [
    formatHeader(results, durationMs), formatOverallStatus(stats, overallStatus),
    formatKeyMetrics(results, stats), formatWarningsAndRisks(results, stats),
    formatActionItems(results, stats), formatFailedProjects(results),
    '---\n*Generated by CloudVoyager*\n',
  ];
  return sections.filter(Boolean).join('\n');
}
