// -------- Performance Report Formatter --------
import { formatSlowestSteps, formatBottleneckAnalysis } from '../perf-tables.js';
import { formatHeader } from './helpers/format-header.js';
import { formatOverview } from './helpers/format-overview.js';
import { formatServerSteps } from './helpers/format-server-steps.js';
import { formatOrgSteps } from './helpers/format-org-steps.js';
import { formatProjectBreakdown } from './helpers/format-project-breakdown.js';
import { formatEnvironment } from './helpers/format-environment.js';
import { formatConfiguration } from './helpers/format-configuration.js';

export function formatPerformanceReport(results) {
  const sections = [
    formatHeader(results), formatOverview(results),
    formatServerSteps(results), formatOrgSteps(results),
    formatProjectBreakdown(results), formatSlowestSteps(results),
    formatBottleneckAnalysis(results), formatEnvironment(results),
    formatConfiguration(results), '---\n*Generated by CloudVoyager*\n',
  ];
  return sections.filter(Boolean).join('\n');
}
