// -------- Verification Markdown Report --------

import { formatHeader } from './helpers/format-header.js';
import { formatSummary } from './helpers/format-summary.js';
import { formatUnsyncableWarnings } from './helpers/format-unsyncable.js';
import { formatOrgResults } from './helpers/format-org-results.js';
import { formatPortfolios } from './helpers/format-portfolios.js';
import { statusIcon } from './helpers/status-icon.js';
import { formatProjectResults } from '../markdown-sections/project-results.js';

/**
 * Format verification results as a markdown report.
 */
export function formatVerificationMarkdown(results) {
  const sections = [];

  sections.push(formatHeader(results));
  sections.push(formatSummary(results));
  sections.push(formatUnsyncableWarnings(results));
  sections.push(formatOrgResults(results));
  sections.push(formatProjectResults(results, statusIcon));
  sections.push(formatPortfolios(results));

  sections.push('---\n*Generated by CloudVoyager Verification*\n');

  return sections.filter(Boolean).join('\n');
}
