import { formatProfileSection } from './helpers/format-profile-section.js';

// -------- Format Rules Comparison Report --------

/** Format the quality profile rules comparison data as a markdown string. */
export function formatRulesComparisonReport(results) {
  if (!results.rulesComparisonData) return null;
  const { generatedAt, summary, languages } = results.rulesComparisonData;

  const lines = [
    '# Quality Profile Rules Comparison Report\n',
    `Generated: ${generatedAt}\n`,
    '## Summary\n',
    '| Metric | Count |',
    '|--------|-------|',
    `| Profiles Compared | ${summary.languagesCompared} |`,
    `| Rules in SonarQube but NOT SonarCloud (will disappear) | ${summary.totalMissingRules} |`,
    `| Rules in SonarCloud but NOT SonarQube (will appear) | ${summary.totalAddedRules} |`,
    '',
    '> **Note:** Missing rules may cause issues raised in SonarQube to disappear in SonarCloud.',
    '> Added rules may cause new issues to appear in SonarCloud that were not in SonarQube.\n',
    '## Per-Profile Comparison\n',
    ...Object.entries(languages).map(([langKey, diff]) => formatProfileSection(langKey, diff)),
    '---\n*Generated by CloudVoyager*\n',
  ];

  return lines.join('\n');
}
