import { formatRuleDiffTables } from './helpers/format-profile-section.js';

// -------- Format Rules Comparison Report --------

/** Format the full rules comparison data (SQ vs SC by Rule ID) as markdown. */
export function formatRulesComparisonReport(results) {
  if (!results.rulesComparisonData) return null;
  const { generatedAt, summary, onlyInSQ, onlyInSC } = results.rulesComparisonData;

  const lines = [
    '# Rules Comparison Report — SonarQube vs SonarCloud\n',
    `Generated: ${generatedAt}\n`,
    '## Summary\n',
    '| Metric | Count |',
    '|--------|-------|',
    `| SonarQube Total Rules | ${summary.sqTotalRules} |`,
    `| SonarCloud Total Rules | ${summary.scTotalRules} |`,
    `| Rules in Both | ${summary.inBothCount} |`,
    `| Only in SonarQube (not in SonarCloud) | ${summary.onlyInSQCount} |`,
    `| Only in SonarCloud (not in SonarQube) | ${summary.onlyInSCCount} |`,
    '',
    ...formatRuleDiffTables(onlyInSQ, onlyInSC),
    '---\n*Generated by CloudVoyager*\n',
  ];

  return lines.join('\n');
}
