name: Sync-Metadata Integration Tests

on:
  workflow_call:

jobs:
  sync-metadata:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - sync-metadata
          - sync-metadata:skip-issue-metadata
          - sync-metadata:skip-hotspot-metadata
          - sync-metadata:skip-quality-profiles
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: ./.github/actions/restore-deps

      - uses: ./.github/actions/generate-config
        env:
          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARCLOUD_URL: ${{ secrets.SONARCLOUD_URL }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONARCLOUD_ORG_KEY: ${{ secrets.SONARCLOUD_ORG_KEY }}
          SONARCLOUD_ENTERPRISE_KEY: ${{ secrets.SONARCLOUD_ENTERPRISE_KEY }}

      - name: Run ${{ matrix.script }}
        run: npm run ${{ matrix.script }}
